apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo
  namespace: deployment
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: vravilla123/dotnetdemo:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "300Mi"
          requests:
            cpu: "100m"
            memory: "300Mi"
        livenessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - ls
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: ENV_VARIABLE_1
          valueFrom:
            configMapKeyRef:
              name: dotnetdemo-configmap
              key: ENV_VARIABLE_1
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dotnetdemo-secret
              key: SECRET_KEY
