apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dotnetdemo-hpa
  namespace: deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnetdemo
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
