apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo 
  namespace: chow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
        - name: dotnetdemo
          image: venkycontainer.azurecr.io/botnet-web:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: mango
